version = 1

[[annotations]]
path = "xx-color-management-v4.xml"
precedence = "closest"
SPDX-FileCopyrightText = ["Copyright 2019 Sebastian Wick",
                          "Copyright 2019 Erwin Burema",
                          "Copyright 2020 AMD",
                          "Copyright 2020-2024 Collabora, Ltd.",
                          "Copyright 2024 Xaver Hugl"]
SPDX-License-Identifier = "MIT"
